In [1]:
import numpy as np

In [6]:
# Correct way to create a 2D array (5 rows, 5 columns) filled with zeros
zeros = np.zeros((5, 5)) # The shape needs to be passed as a tuple!

# To get the number of dimensions of a NumPy array, use its '.ndim' attribute
num_dimensions = zeros.ndim

print(f"The array:\n{zeros}")
print(f"Number of dimensions (ndim): {num_dimensions}")

The array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Number of dimensions (ndim): 2


In [8]:
# Correct way to create a 2D array (5 rows, 5 columns) filled with ones
# with a specified data type (int8)
ones = np.ones((5, 5), dtype=np.int8)

# To get the number of dimensions, use the '.ndim' attribute
num_dimensions = ones.ndim

print(f"The array:\n{ones}")
print(f"Data type (dtype): {ones.dtype}")
print(f"Number of dimensions (ndim): {num_dimensions}")
# Explanation of the Correction:

# np.ones((5, 5), dtype=np.int8):
# The (5, 5) is now correctly passed as a tuple representing the desired shape (5 rows, 5 columns).
# dtype=np.int8 correctly specifies that the elements should be 8-bit integers.

The array:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Data type (dtype): int8
Number of dimensions (ndim): 2


In [9]:
# 1 dimensional array is a vector
# 2 dimensional array is a matrix
# 3 dimensional array is a 3d matrix
# > 3 dimensional arrays -> NDarray (n-dimensional)

In [ ]:
''' 
Let's explore two more useful NumPy array creation functions: np.full() and np.eye().

np.full(): Create an array filled with a specific value
The np.full() function allows you to create a new array of a specified shape and dtype, and 
fill all its elements with a designated fill_value. 
This is a more generalized version of np.zeros() (which fills with 0) and np.ones() (which fills with 1).


numpy.full(shape, fill_value, dtype=None, order='C')
Parameters:

shape (required): An integer or a tuple of integers specifying the dimensions of the array. (Remember: use a tuple for multi-dimensional arrays!).
fill_value (required): The value you want to fill the entire array with.
dtype (optional): The desired data type for the array elements. If not specified, NumPy infers it from the fill_value.
order (optional): 'C' (default) for C-style row-major order, 'F' for Fortran-style column-major order.'
'''

In [11]:
import numpy as np

# Create a 1D array of 5 eights (default float dtype inferred from 8.0)
arr1_full = np.full(5, 8.0)
print("1D array filled with 8.0s:\n", arr1_full)
# Output: [8. 8. 8. 8. 8.]

# Create a 2D array (2 rows, 3 columns) filled with the number 7 (integer dtype inferred)
arr2_full = np.full((2, 3), 7)
print("\n2D array filled with 7s:\n", arr2_full)
# Output:
# [[7 7 7]
#  [7 7 7]]

# Create a 3D array filled with boolean True values
arr3_full = np.full((2, 2, 2), True, dtype=bool)
print("\n3D array filled with Trues:\n", arr3_full)
# Output:
# [[[ True  True]
#   [ True  True]]
#
#  [[ True  True]
#   [ True  True]]]

# Create an array filled with a string
arr_str_full = np.full((2, 2), "hello")
print("\nArray filled with strings:\n", arr_str_full)
# Output:
# [['hello' 'hello']
#  ['hello' 'hello']]

1D array filled with 8.0s:
 [8. 8. 8. 8. 8.]

2D array filled with 7s:
 [[7 7 7]
 [7 7 7]]

3D array filled with Trues:
 [[[ True  True]
  [ True  True]]

 [[ True  True]
  [ True  True]]]

Array filled with strings:
 [['hello' 'hello']
 ['hello' 'hello']]


In [ ]:
''' 
np.eye(): Create an identity matrix (or related diagonal matrix)
The np.eye() function creates a 2-dimensional array with ones on a specified diagonal and zeros everywhere else. It's particularly useful for creating identity matrices, which are fundamental in linear algebra.

Syntax:

Python

numpy.eye(N, M=None, k=0, dtype=float, order='C')
Parameters:

N (required): The number of rows in the output array.
M (optional): The number of columns in the output array. If None (default), M defaults to N, creating a square matrix.
k (optional): The index of the diagonal.
k = 0 (default): The main diagonal.
k > 0: Diagonals above the main diagonal.
k < 0: Diagonals below the main diagonal.
dtype (optional): The desired data type for the array elements. Defaults to float64.
order (optional): 'C' (default) or 'F'.


Examples:
'''

In [10]:
import numpy as np

# 1. Create a 3x3 identity matrix (main diagonal, default float)
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:\n", identity_matrix)
# Output:
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]

# 2. Create a 4x5 rectangular matrix with the main diagonal
rect_eye = np.eye(4, 5)
print("\n4x5 rectangular matrix with main diagonal:\n", rect_eye)
# Output:
# [[1. 0. 0. 0. 0.]
#  [0. 1. 0. 0. 0.]
#  [0. 0. 1. 0. 0.]
#  [0. 0. 0. 1. 0.]]

# 3. Shift the diagonal up (k=1)
shifted_up_eye = np.eye(3, k=1)
print("\n3x3 matrix with diagonal shifted up (k=1):\n", shifted_up_eye)
# Output:
# [[0. 1. 0.]
#  [0. 0. 1.]
#  [0. 0. 0.]]

# 4. Shift the diagonal down (k=-1)
shifted_down_eye = np.eye(3, k=-1)
print("\n3x3 matrix with diagonal shifted down (k=-1):\n", shifted_down_eye)
# Output:
# [[0. 0. 0.]
#  [1. 0. 0.]
#  [0. 1. 0.]]

# 5. Create an integer identity matrix
int_identity = np.eye(2, dtype=int)
print("\n2x2 integer identity matrix:\n", int_identity)
# Output:
# [[1 0]
#  [0 1]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4x5 rectangular matrix with main diagonal:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]

3x3 matrix with diagonal shifted up (k=1):
 [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]

3x3 matrix with diagonal shifted down (k=-1):
 [[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]

2x2 integer identity matrix:
 [[1 0]
 [0 1]]


In [ ]:
'''
Both np.full() and np.eye() are valuable tools for initializing arrays with specific patterns, 
which is a common task in numerical computing and data manipulation.
'''

In [ ]:
# Creat an numpy array of shape (100, 100, 3), a 3D matrix
# and later initialize the array

# Numpy built-in function we learned today creates and initiate array at once. 
# But we need options to create an empty array and later initialize. 

# that is where np.empty(shape) helps. 

In [ ]:
'''
np.empty(shape) is a NumPy function that creates a new array of a given shape and dtype (defaulting to float), but its elements are not initialized.

This means that the array will contain whatever values were already present in the memory locations it allocates. These "random" values are often referred to as garbage values.

Why use np.empty()?

Even though the values are garbage, np.empty() is the fastest way to create a new, uninitialized array in NumPy. This is because it doesn't spend any time setting all the elements to a specific value (like zero for np.zeros() or one for np.ones()).

It's primarily used when you know you're immediately going to fill the array completely with new data through subsequent calculations or assignments, making the initial "garbage" values irrelevant. If you need to ensure all elements are a specific value (like 0 or 1), np.zeros() or np.ones() are safer and more appropriate.


Syntax:

numpy.empty(shape, dtype=float, order='C')


Parameters:

shape (required): An integer or a tuple of integers specifying the dimensions of the array. (Remember to use a tuple for multi-dimensional arrays!).
dtype (optional): The desired data type for the array elements. Defaults to float64.
order (optional): 'C' for C-style row-major order (default), 'F' for Fortran-style column-major order.


'''

'\nnp.empty(shape) is a NumPy function that creates a new array of a given shape and dtype (defaulting to float), but its elements are not initialized.\n\nThis means that the array will contain whatever values were already present in the memory locations it allocates. These "random" values are often referred to as garbage values.\n\nWhy use np.empty()?\n\nEven though the values are garbage, np.empty() is the fastest way to create a new, uninitialized array in NumPy. This is because it doesn\'t spend any time setting all the elements to a specific value (like zero for np.zeros() or one for np.ones()).\n\nIt\'s primarily used when you know you\'re immediately going to fill the array completely with new data through subsequent calculations or assignments, making the initial "garbage" values irrelevant. If you need to ensure all elements are a specific value (like 0 or 1), np.zeros() or np.ones() are safer and more appropriate.\n\nSyntax:\n\nPython\n\nnumpy.empty(shape, dtype=float, order=

In [13]:
import numpy as np

# Create a 1D array of 3 elements (content will be whatever was in memory)
arr1d_empty = np.empty(3)
print("1D empty array (values are garbage):\n", arr1d_empty)
# Output will vary, e.g., [1.0234e-310 3.0145e-312 9.0000e-301]

# Create a 2D array (2 rows, 3 columns) with uninitialized values
arr2d_empty = np.empty((2, 3))
print("\n2D empty array (values are garbage):\n", arr2d_empty)
# Output will vary, e.g.:
# [[6.92488803e-310 6.92488803e-310 6.92488803e-310]
#  [6.92488803e-310 6.92488803e-310 6.92488803e-310]]

# Create an empty array with integer dtype
arr_int_empty = np.empty(4, dtype=int)
print("\nInteger empty array (values are garbage):\n", arr_int_empty)
# Output will vary, e.g.: [0 0 0 0] or [12345 54321 67890 11223] (less predictable)

# Demonstrate immediate filling
new_arr = np.empty((2,2))
new_arr[0,0] = 10
new_arr[0,1] = 20
new_arr[1,0] = 30
new_arr[1,1] = 40
print("\nEmpty array, then filled:\n", new_arr)
# Output:
# [[10. 20.]
#  [30. 40.]]

1D empty array (values are garbage):
 [1. 1. 1.]

2D empty array (values are garbage):
 [[3.47739835e-081 1.21935401e-320 0.00000000e+000]
 [1.35387223e-311 0.00000000e+000 1.78019082e-306]]

Integer empty array (values are garbage):
 [3403141796824350720                2468       2740267903472
   32651513910329601]

Empty array, then filled:
 [[10. 20.]
 [30. 40.]]


In [14]:
''''
Demonstarte np.ones and npempty time.per_counter

You're right to think about timing these operations! '

time.perf_counter() is an excellent choice for measuring short durations, as it provides a high-resolution timer.

Let's demonstrate np.ones() and np.empty() and compare their performance when creating large arrays.'

'''

"'\nDemonstarte np.ones and npempty time.per_counter\n\nYou're right to think about timing these operations! '\n\ntime.perf_counter() is an excellent choice for measuring short durations, as it provides a high-resolution timer.\n\nLet's demonstrate np.ones() and np.empty() and compare their performance when creating large arrays.'\n\n"

In [15]:
import numpy as np
import time

size = (10000, 10000) # A 10,000 x 10,000 matrix = 100 million elements
dtype = np.float64   # Using float64 as it's common for numerical data

print(f"Creating arrays of shape {size} with dtype {dtype}\n")

# --- Timing np.ones() ---
start_time_ones = time.perf_counter()
ones_array = np.ones(size, dtype=dtype)
end_time_ones = time.perf_counter()
time_ones = end_time_ones - start_time_ones
print(f"Time taken for np.ones(): {time_ones:.6f} seconds")

# --- Timing np.empty() ---
start_time_empty = time.perf_counter()
empty_array = np.empty(size, dtype=dtype)
end_time_empty = time.perf_counter()
time_empty = end_time_empty - start_time_empty
print(f"Time taken for np.empty(): {time_empty:.6f} seconds")

print("\n--- Verification (first few elements) ---")
print("First 2x2 of ones_array:\n", ones_array[:2, :2])
# empty_array will show arbitrary values as it's not initialized
print("First 2x2 of empty_array (values are uninitialized/garbage):\n", empty_array[:2, :2])

# Optional: Demonstrate filling empty_array (which is when its speed benefit becomes clear)
start_time_fill_empty = time.perf_counter()
empty_array.fill(5.0) # Fill the empty array with a value
end_time_fill_empty = time.perf_counter()
time_fill_empty = end_time_fill_empty - start_time_fill_empty
print(f"\nTime taken to fill empty_array with 5.0: {time_fill_empty:.6f} seconds")
print("First 2x2 of filled empty_array:\n", empty_array[:2, :2])

Creating arrays of shape (10000, 10000) with dtype <class 'numpy.float64'>

Time taken for np.ones(): 0.459213 seconds
Time taken for np.empty(): 0.000172 seconds

--- Verification (first few elements) ---
First 2x2 of ones_array:
 [[1. 1.]
 [1. 1.]]
First 2x2 of empty_array (values are uninitialized/garbage):
 [[0. 0.]
 [0. 0.]]

Time taken to fill empty_array with 5.0: 0.601509 seconds
First 2x2 of filled empty_array:
 [[5. 5.]
 [5. 5.]]


In [ ]:
'''
Expected Output and Explanation:

When you run this code, you will almost always see that:

np.empty() is noticeably faster than np.ones(). This is because np.empty() only allocates the memory for the array; it doesn't bother to write zeros (or any other specific value) into every single element. It just grabs a block of memory and hands it to you as an array.
np.ones() has the extra overhead of initializing every single element in the allocated memory block to 1.0.
The difference in speed becomes more pronounced as the size of the array increases, because the "filling" operation for np.ones() (or np.zeros()) takes a measurable amount of time for a very large number of elements.

The empty_array will print seemingly random floating-point numbers because it's showing whatever bit patterns were already present in the memory locations it acquired. After empty_array.fill(5.0), you'll see it populated with 5.0.

'''

In [ ]:
'''

NumPy's np.random module is a crucial part of the library, providing functions for generating various kinds of pseudo-random numbers. 
It's much faster and more versatile than Python's built-in random module for numerical applications, especially when dealing with arrays.

The np.random module has been refined over time. The modern and recommended way to use it is through a Generator object 
(introduced in NumPy 1.17). This provides better control over reproducibility and allows for different random number generation algorithms.

Here's a brief overview of key functionalities, focusing on the modern approach:

The Recommended Way: numpy.random.default_rng()
You start by creating a Generator instance, typically using np.random.default_rng().

'''

In [ ]:
'''
Syntax : 

import numpy as np

# Create a default random number generator
rng = np.random.default_rng()
Once you have a rng object, you can call various methods on it to generate random numbers.

'''

In [ ]:
# Common rng Methods:


# 1) rng.random(size=None):
#================================================================


#Generates random floats in the half-open interval [0.0, 1.0).
#size: Can be an integer or a tuple for multi-dimensional arrays.
#Python

print("Single random float:", rng.random())
# Output: 0.12345678... (example)

print("\n3 random floats:\n", rng.random(3))
# Output: [0.123 0.456 0.789] (example)

print("\n2x3 array of random floats:\n", rng.random((2, 3)))
# Output:
# [[0.11 0.22 0.33]
#  [0.44 0.55 0.66]] (example)






# 2) rng.integers(low, high=None, size=None, dtype=np.int64):
#================================================================


# Generates random integers from low (inclusive) up to high (exclusive).
# If high is None, integers are generated from 0 to low (exclusive).
# Python

print("\nSingle random integer between 0 and 10 (exclusive):\n", rng.integers(10))
# Output: 7 (example)

print("\n5 random integers between 1 and 10 (exclusive):\n", rng.integers(1, 10, size=5))
# Output: [5 1 8 3 9] (example)

print("\n2x2 array of random integers between 100 and 200 (exclusive):\n", rng.integers(100, 200, size=(2, 2)))
# Output:
# [[145 188]
#  [101 167]] (example)






# 3) rng.normal(loc=0.0, scale=1.0, size=None):
#================================================================


# Generates random numbers from a normal (Gaussian) distribution.
# loc: Mean of the distribution.
# scale: Standard deviation of the distribution.
# Python

print("\n5 random numbers from standard normal distribution (mean=0, std=1):\n", rng.normal(size=5))
# Output: [-0.12 1.05 -0.56 0.89 -0.23] (example)

print("\nRandom number from normal distribution (mean=10, std=2):\n", rng.normal(loc=10, scale=2))
# Output: 9.87 (example)





# 4) rng.choice(a, size=None, replace=True, p=None):
#================================================================


# Generates a random sample from a given 1-D array a.
# a: The array from which to sample.
# replace: If True (default), sampling is done with replacement. If False, without replacement.
# p: Probabilities associated with each entry in a.
# Python

outcomes = ['Heads', 'Tails']
print("\nCoin flip (choice from list):", rng.choice(outcomes))
# Output: 'Heads' (example)

deck = ['Ace', 'King', 'Queen', 'Jack', '10']
print("\nDrawing 3 cards without replacement:\n", rng.choice(deck, size=3, replace=False))
# Output: ['Queen' 'Ace' '10'] (example)







# 5) Reproducibility: Seeding the Generator
#================================================================
# For reproducible results (e.g., in research or testing), you can provide a seed to the default_rng() function.

# Python

# Create a generator with a seed
rng_seeded = np.random.default_rng(seed=42)

print("\nReproducible random numbers (seeded):\n", rng_seeded.random(3))
# Output: [0.77395605 0.43887841 0.85859792]

# If you run this block again with the same seed, you'll get the exact same numbers
rng_seeded_again = np.random.default_rng(seed=42)
print("Same seed, same numbers:\n", rng_seeded_again.random(3))
# Output: [0.77395605 0.43887841 0.85859792]



# Legacy numpy.random module (Discouraged for new code)
# Before NumPy 1.17, functions like np.random.rand(), np.random.randn(), np.random.randint() were directly available. 
# While they still work, the Generator object approach (np.random.default_rng()) is preferred because it offers more robust and explicit control over random number generation.

# In summary, np.random provides powerful tools for generating various types of random numbers, and
#  using np.random.default_rng() is the modern and recommended approach for doing so.

In [ ]:
'''
Let's break down arr.shape, arr.ndim, arr.dtype, and ndarray.itemsize with examples.

First, let's create a sample NumPy array to work with:

Python

import numpy as np

# Create a sample 2D array of integers
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]], dtype=np.int32) # Explicitly set dtype to int32

print("Our sample array 'arr':\n", arr)
print("-" * 30)
arr.shape: The Dimensions of the Array
The shape attribute returns a tuple that indicates the size of the array along each dimension (axis). For a 2D array, it tells you (number of rows, number of columns). For higher dimensions, it extends accordingly.

What it tells you: How many elements are there along each axis.
Type: tuple
Example:

Python

print("arr.shape:", arr.shape)
# Output: arr.shape: (3, 3)
# This means it has 3 rows and 3 columns.

arr_1d = np.array([1, 2, 3, 4, 5])
print("\narr_1d.shape:", arr_1d.shape)
# Output: arr_1d.shape: (5,)
# Note the comma, indicating it's still a tuple of one element.

arr_3d = np.zeros((2, 3, 4)) # A 3D array: 2 "pages", 3 rows, 4 columns
print("\narr_3d.shape:", arr_3d.shape)
# Output: arr_3d.shape: (2, 3, 4)
arr.ndim: Number of Dimensions (Axes)
The ndim attribute returns a single integer indicating the number of dimensions (or axes) of the array.

What it tells you: How many dimensions the array has (e.g., 1 for a vector, 2 for a matrix, 3 for a tensor).
Type: int
Example:

Python

print("arr.ndim:", arr.ndim)
# Output: arr.ndim: 2 (because it's a 2D matrix)

arr_1d = np.array([1, 2, 3, 4, 5])
print("arr_1d.ndim:", arr_1d.ndim)
# Output: arr_1d.ndim: 1

arr_3d = np.zeros((2, 3, 4))
print("arr_3d.ndim:", arr_3d.ndim)
# Output: arr_3d.ndim: 3
arr.dtype: Data Type of Elements
The dtype attribute returns a numpy.dtype object, which describes the type of elements in the array. All elements in a NumPy array must have the same data type (homogeneous).

What it tells you: The type of data stored in each element (e.g., integer, float, boolean, complex).
Type: numpy.dtype object
Example:

Python

print("arr.dtype:", arr.dtype)
# Output: arr.dtype: int32 (as we specified it)

arr_float = np.array([1.1, 2.2, 3.3])
print("\narr_float.dtype:", arr_float.dtype)
# Output: arr_float.dtype: float64 (NumPy's default float)

arr_bool = np.array([True, False])
print("\narr_bool.dtype:", arr_bool.dtype)
# Output: arr_bool.dtype: bool
arr.itemsize: Size of Each Element in Bytes
The itemsize attribute returns an integer representing the size (in bytes) of a single element in the array. This value is determined by the array's dtype.

What it tells you: How much memory (in bytes) each individual element consumes.
Type: int
Example:

Python

print("arr.itemsize:", arr.itemsize, "bytes")
# Output: arr.itemsize: 4 bytes (because int32 uses 4 bytes per integer)

arr_float = np.array([1.1, 2.2, 3.3])
print("\narr_float.itemsize:", arr_float.itemsize, "bytes")
# Output: arr_float.itemsize: 8 bytes (because float64 uses 8 bytes per float)

arr_bool = np.array([True, False])
print("\narr_bool.itemsize:", arr_bool.itemsize, "bytes")
# Output: arr_bool.itemsize: 1 bytes (boolean often uses 1 byte)
Relationship between shape, itemsize, and size (not requested, but related):

You can calculate the total memory occupied by a NumPy array using these attributes:

arr.size: Returns the total number of elements in the array (product of shape elements).
Total Memory (bytes) = arr.size * arr.itemsize
These attributes are essential for understanding, analyzing, and optimizing memory usage and array operations in NumPy.

'''

In [ ]:
'''
Two closely related attributes of NumPy arrays that are crucial for understanding their memory footprint:

arr.itemsize: The size of a single element in the array.
arr.nbytes: The total memory consumed by all the data elements in the array.
Let's demonstrate them with an example:
'''

In [16]:
import numpy as np

# Create an array with a specific dtype
arr = np.array([[1, 2, 3],
                [4, 5, 6]], dtype=np.float32) # Using float32 for demonstration

print("Our sample array 'arr':\n", arr)
print(f"Data type (dtype): {arr.dtype}")
print(f"Shape: {arr.shape}")
print(f"Number of elements (size): {arr.size}")
print("-" * 30)

# --- arr.itemsize ---
# The size in bytes of each individual element in the array.
# It depends entirely on the array's dtype.
print(f"arr.itemsize: {arr.itemsize} bytes (size of one element)")
# For float32, each element takes 4 bytes.

print("-" * 30)

# --- arr.nbytes ---
# The total number of bytes consumed by the array's data.
# This is calculated as: arr.size * arr.itemsize
print(f"arr.nbytes: {arr.nbytes} bytes (total bytes for all elements)")

# Let's verify the calculation:
expected_nbytes = arr.size * arr.itemsize
print(f"Verification: arr.size ({arr.size}) * arr.itemsize ({arr.itemsize}) = {expected_nbytes} bytes")

print("-" * 30)

# Another example with a different dtype
arr_int64 = np.arange(10, dtype=np.int64)
print("\nAnother array 'arr_int64':\n", arr_int64)
print(f"Data type (dtype): {arr_int64.dtype}")
print(f"Number of elements (size): {arr_int64.size}")
print(f"arr_int64.itemsize: {arr_int64.itemsize} bytes")
print(f"arr_int64.nbytes: {arr_int64.nbytes} bytes")

Our sample array 'arr':
 [[1. 2. 3.]
 [4. 5. 6.]]
Data type (dtype): float32
Shape: (2, 3)
Number of elements (size): 6
------------------------------
arr.itemsize: 4 bytes (size of one element)
------------------------------
arr.nbytes: 24 bytes (total bytes for all elements)
Verification: arr.size (6) * arr.itemsize (4) = 24 bytes
------------------------------

Another array 'arr_int64':
 [0 1 2 3 4 5 6 7 8 9]
Data type (dtype): int64
Number of elements (size): 10
arr_int64.itemsize: 8 bytes
arr_int64.nbytes: 80 bytes


In [ ]:
'''
Explanation:

arr.itemsize:

In our first example, arr has dtype=np.float32. A 32-bit floating-point number occupies 4 bytes of memory. So, arr.itemsize is 4.
In the second example, arr_int64 has dtype=np.int64. A 64-bit integer occupies 8 bytes of memory. So, arr_int64.itemsize is 8.
This attribute is constant for all elements within a given NumPy array because NumPy arrays are homogeneous 
(all elements are of the same data type).
arr.nbytes:

This attribute gives you the total memory in bytes that the data within the array consumes.
It's a straightforward multiplication: total_elements * size_of_each_element.
For arr: arr.size is 6 (2 rows * 3 columns), and arr.itemsize is 4 bytes. So, arr.nbytes is 6 * 4 = 24 bytes.
For arr_int64: arr_int64.size is 10, and arr_int64.itemsize is 8 bytes. So, arr_int64.nbytes is 10 * 8 = 80 bytes.
Important Note on nbytes and Views:

While arr.nbytes accurately reflects the memory consumed by the elements of the array as they are represented by its shape and dtype,
 it's important to understand that if your array is a view of another (larger) array (e.g., created by slicing without copying), 
 nbytes will only report the size of the viewed portion, not necessarily the total memory of the underlying original data buffer. 
 For most common uses, however, nbytes will correctly indicate the memory footprint of the array's data.
'''

In [ ]:
# Transpose of an array:

''''
Array transpose is a fundamental operation in linear algebra and data manipulation. 
In NumPy, transposing an array means swapping its rows and columns.

If you have a 2D array (a matrix), transposing it means that the element at (i, j) (row i, column j) 
in the original array moves to position (j, i) (row j, column i) in the transposed array.

For higher-dimensional arrays, it means permuting the axes. The general rule is that the 
i-th axis of the original array becomes the i-th axis of the transposed array.

NumPy provides several convenient ways to transpose an array:

1. The .T attribute (Most Common and Idiomatic)
This is the quickest and most commonly used way to transpose an array. 
It's a property (attribute) of the NumPy array object.

Example:
'''

In [17]:
import numpy as np

# Original 2D array (3 rows, 2 columns)
matrix = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

print("Original Matrix (shape:", matrix.shape, "):\n", matrix)

# Transpose using .T
transposed_matrix = matrix.T
print("\nTransposed Matrix (.T) (shape:", transposed_matrix.shape, "):\n", transposed_matrix)

Original Matrix (shape: (3, 2) ):
 [[1 2]
 [3 4]
 [5 6]]

Transposed Matrix (.T) (shape: (2, 3) ):
 [[1 3 5]
 [2 4 6]]


In [ ]:
# Important Note: .T returns a view of the original array, not a copy. 
# This means if you modify the transposed array, the original array will also be modified (and vice-versa).

In [18]:
matrix = np.array([[1, 2], [3, 4]])
transposed = matrix.T
print("Original before change:\n", matrix)
print("Transposed before change:\n", transposed)

transposed[0, 1] = 99 # Modify an element in the transposed view

print("\nOriginal after change to transposed:\n", matrix)
print("Transposed after change:\n", transposed)

Original before change:
 [[1 2]
 [3 4]]
Transposed before change:
 [[1 3]
 [2 4]]

Original after change to transposed:
 [[ 1  2]
 [99  4]]
Transposed after change:
 [[ 1 99]
 [ 2  4]]


In [23]:
test = np.full((3,5), 2)
test_T = test.T
print(test)
print(test_T)
print(test.shape)
print(test_T.shape)

test_T[1,1] = 100
print(test)
print(test_T)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
[[2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]
(3, 5)
(5, 3)
[[  2   2   2   2   2]
 [  2 100   2   2   2]
 [  2   2   2   2   2]]
[[  2   2   2]
 [  2 100   2]
 [  2   2   2]
 [  2   2   2]
 [  2   2   2]]


In [ ]:
### AGAIN, REPEATING: 
# Important Note: .T returns a view of the original array, not a copy. 
# This means if you modify the transposed array, the original array will also be modified (and vice-versa).

In [ ]:
'''
2. The np.transpose() function
This is a more general function that allows for more complex permutations of axes in higher-dimensional arrays. For a 2D array, without specifying the axes argument, it behaves identically to .T.

Syntax: np.transpose(a, axes=None)

a: The input array.
axes: A tuple of integers, specifying the new order of axes. For a 2D array, (1, 0) means swap axis 0 (rows) with axis 1 (columns).

Example:'

'''

In [24]:
matrix = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

# Transpose using np.transpose()
transposed_func = np.transpose(matrix)
print("\nTransposed using np.transpose() (default) (shape:", transposed_func.shape, "):\n", transposed_func)

# Explicitly specifying axes for a 2D array
transposed_axes = np.transpose(matrix, axes=(1, 0))
print("\nTransposed using np.transpose(axes=(1, 0)) (shape:", transposed_axes.shape, "):\n", transposed_axes)


Transposed using np.transpose() (default) (shape: (2, 3) ):
 [[1 3 5]
 [2 4 6]]

Transposed using np.transpose(axes=(1, 0)) (shape: (2, 3) ):
 [[1 3 5]
 [2 4 6]]


In [26]:
matrix = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

# Transpose using np.transpose()
transposed_func = np.transpose(matrix)
print("\nTransposed using np.transpose() (default) (shape:", transposed_func.shape, "):\n", transposed_func)

# Explicitly specifying axes for a 2D array
transposed_axes = np.transpose(matrix, axes=(0, 1))
print("\nTransposed using np.transpose(axes=(0, 1)) (shape:", transposed_axes.shape, "):\n", transposed_axes)


Transposed using np.transpose() (default) (shape: (2, 3) ):
 [[1 3 5]
 [2 4 6]]

Transposed using np.transpose(axes=(0, 1)) (shape: (3, 2) ):
 [[1 2]
 [3 4]
 [5 6]]


In [27]:
'''
3. For Higher Dimensions
The axes argument of np.transpose() becomes crucial for arrays with 3 or more dimensions.

Example (3D array):

Imagine a 3D array representing (Depth, Height, Width).

axis 0: Depth
axis 1: Height
axis 2: Width
If you want to reorder it to (Height, Width, Depth), you'd specify axes=(1, 2, 0).

'''

"\n3. For Higher Dimensions\nThe axes argument of np.transpose() becomes crucial for arrays with 3 or more dimensions.\n\nExample (3D array):\n\nImagine a 3D array representing (Depth, Height, Width).\n\naxis 0: Depth\naxis 1: Height\naxis 2: Width\nIf you want to reorder it to (Height, Width, Depth), you'd specify axes=(1, 2, 0).\n\n"

In [28]:
arr_3d = np.arange(24).reshape((2, 3, 4)) # 2 "pages", 3 rows, 4 columns
print("Original 3D array (shape:", arr_3d.shape, "):\n", arr_3d)
# Output:
# [[[ 0  1  2  3]
#   [ 4  5  6  7]
#   [ 8  9 10 11]]
#
#  [[12 13 14 15]
#   [16 17 18 19]
#   [20 21 22 23]]]

# Swap axis 0 and axis 2, keeping axis 1 in place
# New shape will be (4, 3, 2)
transposed_3d = np.transpose(arr_3d, axes=(2, 1, 0))
print("\nTransposed 3D array (axes=(2, 1, 0)) (shape:", transposed_3d.shape, "):\n", transposed_3d)
# Output (first "page" for brevity):
# [[[ 0 12]
#   [ 4 16]
#   [ 8 20]]
#
#  [[ 1 13]
#   [ 5 17]
#   [ 9 21]]
# ... and so on

Original 3D array (shape: (2, 3, 4) ):
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Transposed 3D array (axes=(2, 1, 0)) (shape: (4, 3, 2) ):
 [[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]


In [ ]:
# INDEXING AND SLICING with array


'''
Indexing and slicing are fundamental operations for accessing and manipulating elements or sub-arrays within NumPy arrays. They work similarly to Python lists but offer much more powerful capabilities for multi-dimensional arrays.

1. Indexing (Accessing Individual Elements)
Indexing in NumPy arrays uses square brackets [] to access elements.

1D Arrays:
Similar to Python lists.

Python

import numpy as np

arr_1d = np.array([10, 20, 30, 40, 50])
print("arr_1d:", arr_1d)

# Accessing elements by index
print("First element:", arr_1d[0])      # Output: 10
print("Third element:", arr_1d[2])      # Output: 30
print("Last element (negative index):", arr_1d[-1]) # Output: 50
2D Arrays (Matrices):
You provide an index for each dimension, separated by commas. [row_index, column_index]

Python

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("\nMatrix:\n", matrix)

# Accessing elements in a 2D array
print("Element at (0, 0):", matrix[0, 0]) # First row, first column -> Output: 1
print("Element at (1, 2):", matrix[1, 2]) # Second row, third column -> Output: 6
print("Element at (2, -1):", matrix[2, -1]) # Third row, last column -> Output: 9
Higher-Dimensional Arrays:
The concept extends to more dimensions, e.g., arr[dim1_idx, dim2_idx, dim3_idx].

2. Slicing (Accessing Sub-arrays)
Slicing allows you to extract portions (sub-arrays) of an array. It uses the colon : operator, similar to Python lists.

The general syntax for slicing along an axis is [start:stop:step].

start: The starting index (inclusive). If omitted, defaults to 0.

stop: The ending index (exclusive). If omitted, defaults to the end of the dimension.

step: The step size (e.g., 2 for every other element). If omitted, defaults to 1.

1D Array Slicing:

Python

arr_1d = np.array([10, 20, 30, 40, 50, 60, 70])
print("\narr_1d for slicing:", arr_1d)

print("Elements from index 2 to 4 (exclusive):", arr_1d[2:5]) # Output: [30 40 50]
print("Elements from beginning to index 3 (exclusive):", arr_1d[:4]) # Output: [10 20 30 40]
print("Elements from index 4 to end:", arr_1d[4:])   # Output: [50 60 70]
print("Every other element:", arr_1d[::2])       # Output: [10 30 50 70]
print("Reversed array:", arr_1d[::-1])         # Output: [70 60 50 40 30 20 10]
2D Array Slicing:
You can slice along each dimension independently, separated by commas.

Python

matrix = np.array([[ 1,  2,  3,  4],
                   [ 5,  6,  7,  8],
                   [ 9, 10, 11, 12],
                   [13, 14, 15, 16]])
print("\nMatrix for slicing:\n", matrix)

# Get rows 0 and 1, all columns
print("\nFirst two rows, all columns:\n", matrix[0:2, :])
# Output:
# [[1 2 3 4]
#  [5 6 7 8]]

# Get all rows, columns 1 and 2
print("\nAll rows, columns 1 and 2:\n", matrix[:, 1:3])
# Output:
# [[ 2  3]
#  [ 6  7]
#  [10 11]
#  [14 15]]

# Get a sub-matrix (rows 1-2, columns 0-1)
print("\nSub-matrix (rows 1-2, cols 0-1):\n", matrix[1:3, 0:2])
# Output:
# [[ 5  6]
#  [ 9 10]]

# Get every other row, and columns 0 and 3
print("\nEvery other row, cols 0 and 3:\n", matrix[::2, [0, 3]]) # Using fancy indexing for columns here
# Output:
# [[ 1  4]
#  [ 9 12]]

# Access a single row or column as a 1D array
print("\nFirst row as 1D array:", matrix[0])        # Output: [1 2 3 4]
print("First column as 1D array:", matrix[:, 0])    # Output: [ 1  5  9 13]
3. Boolean Indexing (Masking)
You can use a boolean array of the same shape as your original array to select elements. Where the boolean array is True, the element is selected; where it's False, it's not. This returns a 1D array of the selected elements.

Python

data = np.array([10, 15, 20, 25, 30, 35])
print("\nData for boolean indexing:", data)

# Select elements greater than 20
mask = (data > 20)
print("Boolean mask:", mask)       # Output: [False False False  True  True  True]
selected_elements = data[mask]
print("Elements > 20:", selected_elements) # Output: [25 30 35]

# Direct application
print("Even numbers:", data[data % 2 == 0]) # Output: [10 20 30]
4. Fancy Indexing
Fancy indexing uses an array of integers (or a list of integers) as indices. This allows you to select elements or rows/columns in arbitrary order, or to select non-contiguous elements.

Python

arr = np.array([100, 101, 102, 103, 104, 105])
print("\nArray for fancy indexing:", arr)

# Select elements at specific indices
indices = [0, 4, 1]
selected_fancy = arr[indices]
print("Elements at specific indices:", selected_fancy) # Output: [100 104 101]

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("\nMatrix for fancy indexing:\n", matrix)

# Select specific rows
rows_to_select = [0, 2]
print("Selected rows:\n", matrix[rows_to_select])
# Output:
# [[1 2 3]
#  [7 8 9]]

# Select specific elements using a 2D array of indices (tricky, but powerful)
# (row_index, col_index) pairs
coords = np.array([[0, 0], [1, 2], [2, 1]]) # Select (0,0), (1,2), (2,1)
# print("Elements at specific (row, col) pairs:", matrix[coords[:,0], coords[:,1]])
# This is equivalent to matrix[[0,1,2], [0,2,1]]
print("Elements at specific (row, col) pairs:", matrix[[0, 1, 2], [0, 2, 1]])
# Output: [1 6 8] (element at (0,0), element at (1,2), element at (2,1))
Important Consideration: Views vs. Copies
Slicing (Basic Indexing): Slicing usually returns a view of the original array. This means if you modify the slice, the original array will also be modified.
Boolean Indexing: Returns a copy of the array.
Fancy Indexing: Returns a copy of the array.
If you need a copy of a slice from basic indexing, explicitly use .copy(): my_slice = original_array[start:stop].copy().

Mastering indexing and slicing is key to efficiently manipulating data in NumPy, which is fundamental for data science and numerical computing.


'''

In [29]:
import numpy as np

# 1. Define a 3x3 matrix with values from 1 to 9 in order
# We can use np.arange and then reshape it.
matrix = np.arange(1, 10).reshape(3, 3)

print("Original Matrix (3x3):\n", matrix)
print("-" * 30)

# 2. Apply the slicing: mat[::1, ::-1]
# Let's break down the slice:
#   First part: `::1` -> Applies to rows (axis 0)
#     - `start`: omitted, so 0 (beginning)
#     - `stop`: omitted, so end of axis
#     - `step`: 1 (every row)
#     This means: select all rows in their original order.

#   Second part: `::-1` -> Applies to columns (axis 1)
#     - `start`: omitted, so beginning (which for a negative step means the last element)
#     - `stop`: omitted, so end of axis (which for a negative step means the first element)
#     - `step`: -1 (reverse order)
#     This means: select all columns in reverse order.

result_matrix = matrix[::1, ::-1]

print("Result after mat[::1, ::-1]:\n", result_matrix)

Original Matrix (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------
Result after mat[::1, ::-1]:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [30]:
import numpy as np

# 1. Define a 3x3 matrix with values from 1 to 9 in order
# We can use np.arange and then reshape it.
matrix = np.arange(1, 10).reshape(3, 3)

print("Original Matrix (3x3):\n", matrix)
print("-" * 30)

# 2. Apply the slicing: mat[::1, ::-1]
# Let's break down the slice:
#   First part: `::1` -> Applies to rows (axis 0)
#     - `start`: omitted, so 0 (beginning)
#     - `stop`: omitted, so end of axis
#     - `step`: 1 (every row)
#     This means: select all rows in their original order.

#   Second part: `::-1` -> Applies to columns (axis 1)
#     - `start`: omitted, so beginning (which for a negative step means the last element)
#     - `stop`: omitted, so end of axis (which for a negative step means the first element)
#     - `step`: -1 (reverse order)
#     This means: select all columns in reverse order.

result_matrix = matrix[::1, ::1]

print("Result after mat[::1, ::-1]:\n", result_matrix)

Original Matrix (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------
Result after mat[::1, ::-1]:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
import numpy as np

# Original 3x3 matrix
matrix = np.arange(1, 10).reshape(3, 3)

print("Original Matrix (3x3):\n", matrix)
print("-" * 30)

# Slicing to reverse both rows and columns
# First part: `[::-1]` for rows (axis 0) -> reverses the row order
# Second part: `[::-1]` for columns (axis 1) -> reverses the column order
result_matrix = matrix[::-1, ::-1]

print("Result after matrix[::-1, ::-1]:\n", result_matrix)

Original Matrix (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------
Result after matrix[::-1, ::-1]:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [ ]:
# Boolean Indexing
'''



Boolean indexing (also known as boolean masking) is a powerful and very common way to select elements from a NumPy array based on a condition. Instead of using integer indices, you use a boolean array of the same shape as your original array. Where the boolean array is True, the corresponding element from the original array is selected; where it's False, it's not.

This operation effectively "masks" the array, showing only the elements that meet your criteria. The result of boolean indexing is always a 1-dimensional array containing the selected elements.

How it Works:
Create a boolean mask: You typically get a boolean mask by performing a comparison operation on your NumPy array (e.g., arr > 5, arr % 2 == 0). This operation will return a new boolean array of the same shape as arr.
Apply the mask: You then use this boolean mask inside the square brackets [] to index your original array.
Examples:
1. Basic Boolean Indexing (1D Array):

Python

import numpy as np

data = np.array([10, 15, 20, 25, 30, 35, 40])
print("Original 1D data:", data)

# Create a boolean mask: select elements greater than 25
mask = (data > 25)
print("Boolean mask (data > 25):", mask)

# Apply the mask to select elements
selected_elements = data[mask]
print("Selected elements (data > 25):", selected_elements)
# Output: [30 35 40]

print("\n--- Direct application ---")
# You can apply the condition directly without an intermediate mask variable
even_numbers = data[data % 2 == 0]
print("Even numbers:", even_numbers)
# Output: [10 20 30 40]

# Select numbers between 20 and 35 (inclusive)
between_20_and_35 = data[(data >= 20) & (data <= 35)] # Use '&' for AND in NumPy (not 'and')
print("Numbers between 20 and 35:", between_20_and_35)
# Output: [20 25 30 35]
2. Boolean Indexing with 2D Arrays:

Even with multi-dimensional arrays, boolean indexing flattens the result into a 1D array.

Python

matrix = np.array([[ 1,  2,  3],
                   [ 4,  5,  6],
                   [ 7,  8,  9]])
print("\nOriginal 2D matrix:\n", matrix)

# Select all elements greater than 5
mask_gt_5 = (matrix > 5)
print("Boolean mask (matrix > 5):\n", mask_gt_5)

elements_gt_5 = matrix[mask_gt_5]
print("Elements > 5 (1D array):\n", elements_gt_5)
# Output: [6 7 8 9]

# Select even numbers from the matrix
even_elements = matrix[matrix % 2 == 0]
print("Even elements from matrix:\n", even_elements)
# Output: [2 4 6 8]
3. Using ~ for NOT:

You can use the tilde operator ~ to negate a boolean mask (select elements that don't meet the condition).

Python

data = np.array([10, 15, 20, 25])
print("\nData for negation:", data)

mask_less_than_20 = (data < 20)
print("Mask (data < 20):", mask_less_than_20)

not_less_than_20 = data[~mask_less_than_20]
print("Elements NOT < 20:", not_less_than_20)
# Output: [20 25] (which are >= 20)
Key Advantages of Boolean Indexing:
Expressive: It allows you to select data based on logical conditions in a very intuitive way.
Concise: Often requires less code than explicit loops or complex conditional statements.
Efficient: Implemented in optimized C code under the hood, making it very fast for large arrays.
Powerful: Can be combined with other indexing methods (though the result of boolean indexing itself is always 1D).
Boolean indexing is a cornerstone of data filtering and manipulation in NumPy and libraries built on top of it, like Pandas.

'''

In [ ]:
''''
NumPy's np.where() function is a powerful and versatile tool for conditional selection, often used in conjunction with indexing. While boolean indexing directly gives you the values that satisfy a condition, np.where() gives you the indices (or coordinates) where a condition is met, and can also perform element-wise conditional assignment.

How np.where() Works
np.where() can be used in two main ways:

To get indices where a condition is True:
np.where(condition)
This returns a tuple of arrays, one array for each dimension, indicating the indices of the elements where condition is True.

To perform element-wise conditional selection (like a vectorized if-else):
np.where(condition, x, y)
This returns an array with elements chosen from x where condition is True, and elements chosen from y where condition is False. x and y can be scalars or arrays of the same shape as condition.

1. Using np.where() to Get Indices
This is useful when you need the locations of elements that meet a criterion, rather than just the elements themselves.

Example (1D Array):

Python

import numpy as np

arr = np.array([10, 5, 20, 15, 30, 8])
print("Original array:", arr)

# Find indices where elements are greater than 10
indices_gt_10 = np.where(arr > 10)
print("Indices where elements > 10:", indices_gt_10)
# Output: (array([2, 3, 4]),) - A tuple containing one array of indices

# You can use these indices with regular indexing
elements_at_indices = arr[indices_gt_10]
print("Elements at those indices:", elements_at_indices)
# Output: [20 15 30]
Example (2D Array):

For 2D (or higher) arrays, np.where(condition) returns a tuple of arrays, where each array corresponds to a dimension's indices.

Python

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("\nOriginal matrix:\n", matrix)

# Find indices where elements are even
row_indices, col_indices = np.where(matrix % 2 == 0)

print("Row indices of even elements:", row_indices)
# Output: [0 1 1 2]
print("Column indices of even elements:", col_indices)
# Output: [1 0 2 1]

# To get the actual (row, col) pairs:
print("Coordinates of even elements:")
for r, c in zip(row_indices, col_indices):
    print(f"({r}, {c}) -> {matrix[r, c]}")
# Output:
# (0, 1) -> 2
# (1, 0) -> 4
# (1, 2) -> 6
# (2, 1) -> 8
2. Using np.where() for Conditional Assignment (Vectorized If-Else)
This is where np.where(condition, x, y) shines, allowing you to create new arrays (or modify existing ones) based on conditions without explicit loops.

Example (Simple conditional value):

Python

scores = np.array([85, 92, 60, 78, 45, 95])
print("Scores:", scores)

# Assign 'Pass' if score >= 70, else 'Fail'
grades = np.where(scores >= 70, 'Pass', 'Fail')
print("Grades:", grades)
# Output: ['Pass' 'Pass' 'Fail' 'Pass' 'Fail' 'Pass']
Example (Applying functions conditionally):

Python

data = np.array([-2, 5, -1, 8, 0, -3])
print("\nOriginal data:", data)

# Replace negative numbers with 0, keep positive numbers as they are
positive_data = np.where(data < 0, 0, data)
print("Negative numbers replaced with 0:", positive_data)
# Output: [0 5 0 8 0 0]

# Square even numbers, leave odd numbers as is
numbers = np.array([1, 2, 3, 4, 5, 6])
squared_evens = np.where(numbers % 2 == 0, numbers**2, numbers)
print("Squared evens, odds unchanged:", squared_evens)
# Output: [ 1  4  3 16  5 36]
Example (Conditional assignment in 2D array):

Python

matrix = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])
print("\nOriginal matrix:\n", matrix)

# If element > 50, replace with 0, otherwise keep original
modified_matrix = np.where(matrix > 50, 0, matrix)
print("Matrix with elements > 50 replaced by 0:\n", modified_matrix)
# Output:
# [[10 20 30]
#  [40 50  0]
#  [ 0  0  0]]
Key Differences from Direct Boolean Indexing:
Output Shape:

Direct Boolean Indexing (arr[condition]): Always returns a 1D array (flattened).
np.where(condition, x, y): Returns an array with the same shape as condition (or x and y).
np.where(condition): Returns a tuple of index arrays, one for each dimension.
Purpose:

Direct Boolean Indexing: Primarily for filtering elements out of an array to get a subset.
np.where(condition, x, y): Primarily for transforming an array based on conditions, often to create a new array or conditionally replace values.
np.where(condition): Primarily for locating the positions of elements that meet a condition.
np.where() is an incredibly versatile function for conditional logic in NumPy, often leading to more efficient and readable code than explicit Python loops.'

'''

In [ ]:
# Array reshaping and resizing
#==============================

'''
In NumPy, "reshaping" and "resizing" arrays are distinct but related concepts, often causing confusion. Let's clarify them.

Array Reshaping (.reshape(), .resize(), np.reshape())
Reshaping changes the shape (dimensions) of an array without changing its data or the total number of elements. It creates a new view of the original array's data with a different arrangement.

Key characteristics:

Total elements must remain the same: original_shape_product = new_shape_product.
Returns a view (usually): The new array typically shares the same underlying data buffer with the original array. Modifying one will affect the other. If a view is not possible (e.g., due to memory layout), a copy might be returned, but this is less common for simple reshaping.
Commonly used for: Changing a 1D array into a 2D matrix, or vice versa, or adjusting the dimensions of higher-dimensional arrays for specific operations (e.g., matrix multiplication).
Methods for Reshaping:
arr.reshape(new_shape) (Recommended):
This is the most common and clear way to reshape an array.

Python

import numpy as np

arr_1d = np.arange(1, 13) # 1D array with 12 elements
print("Original 1D array:\n", arr_1d)
print("Shape:", arr_1d.shape) # (12,)

# Reshape to 3 rows, 4 columns
matrix_3x4 = arr_1d.reshape(3, 4)
print("\nReshaped to 3x4 matrix:\n", matrix_3x4)
print("Shape:", matrix_3x4.shape) # (3, 4)

# Reshape back to 2 rows, 6 columns
matrix_2x6 = arr_1d.reshape((2, 6)) # Can use a tuple for shape
print("\nReshaped to 2x6 matrix:\n", matrix_2x6)
print("Shape:", matrix_2x6.shape) # (2, 6)

# Using -1 to infer a dimension:
# -1 means NumPy will calculate the size of that dimension
matrix_unknown_rows = arr_1d.reshape(-1, 4) # 4 columns, infer rows
print("\nReshaped to (-1, 4) (inferred rows):\n", matrix_unknown_rows)
print("Shape:", matrix_unknown_rows.shape) # (3, 4)

matrix_unknown_cols = arr_1d.reshape(3, -1) # 3 rows, infer columns
print("\nReshaped to (3, -1) (inferred columns):\n", matrix_unknown_cols)
print("Shape:", matrix_unknown_cols.shape) # (3, 4)

# Demonstrate view vs copy:
matrix_3x4[0, 0] = 99
print("\nOriginal array after modifying its reshape-view:\n", arr_1d)
# Output: [99  2  3  4  5  6  7  8  9 10 11 12] (arr_1d is modified!)
np.reshape(arr, new_shape):
This is a function that achieves the same result as the method. It's often used when you don't have the array as an object yet or prefer a functional style.

Python

arr_2d_func = np.reshape(arr_1d, (4, 3))
print("\nReshaped using np.reshape function:\n", arr_2d_func)
print("Shape:", arr_2d_func.shape) # (4, 3)
arr.resize(new_shape) (In-place modification - BE CAREFUL):
This method modifies the array in-place and can change the total number of elements.

If the new size is larger, the new elements will be filled with zeros (for numerical dtypes) or garbage values.
If the new size is smaller, elements are truncated.
It can only be called if no other variables are referencing the array! If there are other views or references, it will raise a ValueError. This makes it less commonly used than .reshape().
Python

# Example for resize (careful with existing references)
a = np.array([1, 2, 3, 4, 5])
print("\nOriginal 'a' for resize:", a)
print("Shape:", a.shape)

a.resize(3) # Reduces size
print("a after resize(3):\n", a)
print("Shape:", a.shape) # (3,)

b = np.array([1, 2, 3])
b.resize(5) # Increases size, new elements are zeros
print("b after resize(5):\n", b)
print("Shape:", b.shape) # (5,)
Array Resizing (Conceptual, often means np.resize() or arr.resize())
Resizing (in the context of NumPy's np.resize() function or the arr.resize() method) means changing the total number of elements in the array. This typically involves creating a new array and copying the old data (for np.resize()) or modifying in-place (for arr.resize()).

Method for Resizing (with potential data change):
np.resize(a, new_shape) (Returns a copy):
This function returns a new array with the specified new_shape.

If the new array is larger, it will fill the additional space by repeating the existing data from the original array.
If the new array is smaller, it truncates the data.
Crucially, it always returns a copy, so the original array is unaffected.
Python

arr = np.array([1, 2, 3, 4])
print("\nOriginal array for np.resize:", arr)
print("Shape:", arr.shape)

# Resize to a larger shape, data is repeated
resized_larger = np.resize(arr, (2, 3)) # New shape (2,3) means 6 elements
print("\nResized larger (np.resize):\n", resized_larger)
print("Shape:", resized_larger.shape) # (2, 3)
# Output:
# [[1 2 3]
#  [4 1 2]]  (Note the 1 and 2 are repeated from the beginning)

# Resize to a smaller shape, data is truncated
resized_smaller = np.resize(arr, 2)
print("\nResized smaller (np.resize):\n", resized_smaller)
print("Shape:", resized_smaller.shape) # (2,)
# Output: [1 2]
Summary of Differences:
Feature	Reshaping (.reshape(), np.reshape())	Resizing (arr.resize(), np.resize())
Data Count	Same number of elements	Can change the number of elements
Returns	Usually a view (shared data)	np.resize(): copy; arr.resize(): None (in-place)
Effect	Changes how data is interpreted	Changes the amount of data and shape
Memory	No new memory allocation (mostly)	New memory allocation and data copying/truncation
Error	Fails if total elements don't match	arr.resize() fails if views exist
Use Case	Structuring data for operations	Changing array size, potentially repeating/truncating data



'''

In [ ]:
# Flatterni an array abd ravel an array 

'''
Flattening an array in NumPy means converting a multi-dimensional array (like a 2D matrix or a 3D tensor) into a 1-dimensional array while preserving the order of the elements.

NumPy provides several convenient methods to achieve this:

1. arr.flatten() (Returns a copy)
This is a method of the ndarray object. It always returns a new, flattened copy of the array. Changes to the flattened array will not affect the original, and vice versa. The elements are read in row-major order (C-style order) by default.

Syntax: arr.flatten(order='C')

order: 'C' for row-major (C-style) order (default), 'F' for column-major (Fortran-style) order, 'A' for 'a'scending or 'F'ortran-style order if array is Fortran contiguous in memory, 'K' for element order as they appear in memory.
Example:

Python

import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Original Matrix:\n", matrix)

# Flatten in row-major (C-style) order (default)
flat_c_order = matrix.flatten()
print("\nFlattened (C-order, copy):\n", flat_c_order)
# Output: [1 2 3 4 5 6 7 8 9]

# Flatten in column-major (Fortran-style) order
flat_f_order = matrix.flatten(order='F')
print("Flattened (F-order, copy):\n", flat_f_order)
# Output: [1 4 7 2 5 8 3 6 9]

# Demonstrate that it's a copy
flat_c_order[0] = 999
print("\nModified flattened copy:", flat_c_order)
print("Original Matrix (unchanged):\n", matrix)
2. arr.ravel() (Returns a view or copy)
This is also a method of the ndarray object. It returns a flattened view of the original array whenever possible. If a view is not possible (e.g., if the array's memory layout is not contiguous after certain operations), it will return a copy. The elements are also read in row-major order by default.

Syntax: arr.ravel(order='C')

order: Same as flatten().
Example:

Python

import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Original Matrix:\n", matrix)

# Ravel in row-major (C-style) order (default)
flat_ravel = matrix.ravel()
print("\nRaveled (C-order, view if possible):\n", flat_ravel)
# Output: [1 2 3 4 5 6 7 8 9]

# Demonstrate that it's often a view
flat_ravel[0] = 999
print("\nModified raveled view:", flat_ravel)
print("Original Matrix (CHANGED!):\n", matrix) # Original matrix is affected
Key Difference between flatten() and ravel():

flatten() always returns a copy.
ravel() returns a view if possible, otherwise a copy.
Use flatten() when you explicitly need an independent copy.
Use ravel() when you want the most memory-efficient operation and don't mind if modifications affect the original (or if you won't modify it).
3. np.reshape(-1) or arr.reshape(-1)
This is a concise way to flatten an array using the reshape function/method. When you provide -1 as the shape argument, NumPy automatically infers the dimension, which in this case means flattening the array into a 1D array.

Syntax: arr.reshape(-1) or np.reshape(arr, -1)

Like ravel(), reshape(-1) returns a view if possible, otherwise a copy.
Example:

Python

import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Original Matrix:\n", matrix)

flat_reshaped = matrix.reshape(-1)
print("\nFlattened using reshape(-1):\n", flat_reshaped)
# Output: [1 2 3 4 5 6 7 8 9]

# This also typically returns a view
flat_reshaped[0] = 777
print("\nModified reshaped view:", flat_reshaped)
print("Original Matrix (CHANGED!):\n", matrix) # Original matrix is affected


Summary of Flattening Methods:
Method	             Returns	Memory Efficiency	                Modifications Affect Original?
arr.flatten()	      Copy	     Less (new memory)	                          No
arr.ravel()	          View      (if possible) More (no new memory)	          Yes
arr.reshape(-1)	      View      (if possible)More (no new memory)	          Yes


'''

In [ ]:
# Squeeze
'''
The NumPy function np.squeeze() is used to remove single-dimensional entries (or "singleton dimensions") from the shape of an array.

In simpler terms, if an array has a dimension with a size of 1, np.squeeze() will get rid of that dimension, effectively "squeezing" the array to a lower dimension.

Syntax:

Python

numpy.squeeze(a, axis=None)
Parameters:

a (required): The input array.
axis (optional): A single integer or a tuple of integers. If specified, only the dimensions listed in axis are squeezed. Dimensions not listed, or dimensions with a size greater than 1, will not be removed. If None (default), all single-dimensional entries are removed.
How it Works (and doesn't work):

np.squeeze() will only remove dimensions that have a length of 1.
It will not remove dimensions with a length greater than 1.
It will not remove dimensions with a length of 0 (empty dimensions), though such arrays are rare.
Examples:

Squeezing all single-dimensional entries (default behavior):

Python

import numpy as np

# A 3D array with singleton dimensions
arr_3d = np.array([[[1, 2, 3]]])
print("Original 3D array:\n", arr_3d)
print("Original shape:", arr_3d.shape) # (1, 1, 3)
print("Original ndim:", arr_3d.ndim)   # 3

squeezed_arr = np.squeeze(arr_3d)
print("\nSqueezed array:\n", squeezed_arr)
print("Squeezed shape:", squeezed_arr.shape) # (3,)
print("Squeezed ndim:", squeezed_arr.ndim)   # 1
In this example, the original array (1, 1, 3) had two dimensions of size 1. np.squeeze() removed both, resulting in a 1D array of shape (3,).

Squeezing a specific axis:

Python

import numpy as np

# A 4D array with multiple dimensions, some singletons
arr_4d = np.zeros((1, 2, 1, 3))
print("Original 4D array:\n", arr_4d)
print("Original shape:", arr_4d.shape) # (1, 2, 1, 3)

# Squeeze only axis 0 (the first dimension)
squeezed_axis_0 = np.squeeze(arr_4d, axis=0)
print("\nSqueezed (axis=0) array:\n", squeezed_axis_0)
print("Squeezed (axis=0) shape:", squeezed_axis_0.shape) # (2, 1, 3)

# Squeeze only axis 2 (the third dimension)
squeezed_axis_2 = np.squeeze(arr_4d, axis=2)
print("\nSqueezed (axis=2) array:\n", squeezed_axis_2)
print("Squeezed (axis=2) shape:", squeezed_axis_2.shape) # (1, 2, 3)

# Squeeze multiple specific axes
squeezed_axes_0_2 = np.squeeze(arr_4d, axis=(0, 2))
print("\nSqueezed (axis=(0, 2)) array:\n", squeezed_axes_0_2)
print("Squeezed (axis=(0, 2)) shape:", squeezed_axes_0_2.shape) # (2, 3)

# Attempt to squeeze an axis that is not a singleton (will raise an error)
try:
    np.squeeze(arr_4d, axis=1) # Axis 1 has size 2
except ValueError as e:
    print(f"\nError when squeezing non-singleton axis: {e}")
This demonstrates that if you specify an axis that does not have a length of 1, np.squeeze() will raise a ValueError.

Common Use Cases:

After operations that add singleton dimensions: Some NumPy operations (like np.newaxis or broadcasting) might result in arrays with extra dimensions of size 1. np.squeeze() helps clean up the shape.
Preparing data for models: Many machine learning models expect specific input shapes (e.g., (batch_size, features) instead of (batch_size, 1, features)).
Simplifying array shapes: Making your array shapes more intuitive and easier to work with.
np.squeeze() is a powerful tool for managing the dimensionality of your NumPy arrays, making your code cleaner and your array operations more straightforward.'


'''